name: Multi-platform Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # Define target artifact name based on OS for consistency
        include:
          - os: ubuntu-latest
            artifact_name: harbor-migration-linux-x86_64
          - os: windows-latest
            artifact_name: harbor-migration-windows-x86_64.exe
          - os: macos-latest
            artifact_name: harbor-migration-macos-x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build release binary
        run: cargo build --release

      - name: Rename binary for artifact upload
        shell: bash # Use bash on all platforms for consistent scripting
        run: |
          # Use a shell script to find and rename the built binary correctly
          APP_NAME="harbor-migration" # Replace with your project's binary name
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            find target/release/ -maxdepth 1 -name "*.exe" -exec mv {} target/release/${{ matrix.artifact_name }} \;
          else
            find target/release/ -maxdepth 1 -type f ! -name "*.d" ! -name "*.rlib" -exec mv {} target/release/${{ matrix.artifact_name }} \;
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/release/${{ matrix.artifact_name }}
